<?php
// refresh site on post update
function call_hook($url){
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();
	curl_setopt($ch, CURLOPT_URL, $url);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_POST, 1);
	$headers = array();
	$headers[] = "Content-Type: application/x-www-form-urlencoded";
	$headers[] = "Content-length: 0";
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	$result = curl_exec($ch);
	if (curl_errno($ch)) {
			error_log('Error:' . curl_error($ch));
	} else {
			error_log($result);
	}
	curl_close ($ch);
	
}

if ( $_SERVER["SERVER_ADDR"] !== '127.0.0.1' ) {//don't update on local env
	function refreshSite($post_id){
		$post = get_post($post_id);
		if($post->post_type != 'registratie'){ // don't refresh site on form submission
			call_hook('https://api.netlify.com/build_hooks/5cbf26858b44e1d95d6e5624');
			call_hook('https://api.netlify.com/build_hooks/5d03b9e137d23eafc06bd90a');
		}
	} add_action( 'save_post', 'refreshSite', 11, 1 );
}