<?php
function my_acf_google_map_api( $api ){
	$api['key'] = 'AIzaSyDujkg0Ss-J1rQFNy-J1B2S7sgcpdbjXek';
	return $api;
} add_filter('acf/fields/google_map/api', 'my_acf_google_map_api');

// refresh site on post update
function refreshSite($post_id){
	$post = get_post($post_id);

	
	if($post->post_type != 'registratie'){ // don't refresh site on form submission
		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL, "https://api.netlify.com/build_hooks/5cbf26858b44e1d95d6e5624");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POST, 1);
		$headers = array();
		$headers[] = "Content-Type: application/x-www-form-urlencoded";
		$headers[] = "Content-length: 0";
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
		$result = curl_exec($ch);
		if (curl_errno($ch)) {
				error_log('Error:' . curl_error($ch));
		} else {
				error_log($result);
		}
		curl_close ($ch);
	}
} add_action( 'save_post', 'refreshSite', 8, 1 );



// give form edit permission to editor
function wpforms_custom_capability( $cap ) {
	// unfiltered_html by default means Editors and up.
	// See more about WordPress roles and capabilities
	// https://codex.wordpress.org/Roles_and_Capabilities
	return 'unfiltered_html';
} add_filter( 'wpforms_manage_cap', 'wpforms_custom_capability' );

// create custom post type for 'registratie'
function registratie_cpt() {
	$args = array(
			'labels'  => array(
				'name' => 'registraties',
				'singular_name' => 'registratie',
			),
			'public' => true,
			// 'show_in_menu' => false
	);
	register_post_type( 'registratie', $args );

} add_action( 'init', 'registratie_cpt' );


// create sub menu page for registraties in activity tab
function my_menu() {
	add_submenu_page('edit.php?post_type=activity', 'Registraties', 'registraties', 'unfiltered_html', 'registraties', 'submissions_page_display' );
} add_action('admin_menu', 'my_menu');

// form submissions page
function submissions_page_display() {
	// if no activity is set, show all activities
	if (isset($_REQUEST['activity_id'])){

		$activity = get_post($_REQUEST['activity_id']);

		if( ! class_exists( 'Submissions_List_Table' ) ) {
			require_once( 'includes/submissions-list-table-class.php' );
		}

		$submissionsListTable = new Submissions_List_Table($activity->ID);
		$submissionsListTable->prepare_items();

		?>
			<div class="wrap">
				<h1>registraties: <a href="post.php?action=edit&post=<?=$activity->ID;?>"><?=$activity->post_title;?></a></h1>
				<a href="edit.php?post_type=activity&page=registraties">terug naar overzicht</a><br/>
				<!-- <a href="">exporteer csv</a> -->
				<?php $submissionsListTable->display(); ?>
				

			</div>
		<?php

	// if activity is set, show submissions
	} else {

		if( ! class_exists( 'Submissions_Overview_List_Table' ) ) {
			require_once( 'includes/submissions-overview-list-table-class.php' );
		}

		$submissionsOverviewListTable = new Submissions_Overview_List_Table();
		$submissionsOverviewListTable->prepare_items();

		?>
			<div class="wrap">
				<h1>registraties</h1>
				<?php $submissionsOverviewListTable->display(); ?>
			</div>
		<?php
	}

	
}

// add rest route to get registration count and limit
add_action('rest_api_init', function () {
	register_rest_route( 'vrp-api/v1', 'activity/submission-count/(?P<id>\d+)',array(
		'methods'  => WP_REST_Server::READABLE,
		'callback' => 'activity_submission_count'
	));
});
// check+return registration count and limit
function activity_submission_count( $data ) {
	$activity_id = $data['id'];

	// $hasform = get_field('hasform', $activity_id);

	$args = array(
		'post_type' => 'registratie',
		'meta_query' => array(
			array(
				'key' => 'activity_id',
				'value' => $activity_id,
				)
			)
	);

	$query = new WP_Query($args);
	$count = $query->found_posts;

	$places = get_field('places', $activity_id);

	$response = new WP_REST_Response(array(
		'count' => $count,
		'places' => $places > 0 ? $places : '-1'
	));
	$response->set_status(200);

	return $response;
}

// add rest route to add form submission
add_action('rest_api_init', function () {
	register_rest_route( 'vrp-api/v1', 'form-submission',array(
		'methods'  => WP_REST_Server::CREATABLE,
		'callback' => 'vrp_form_submission'
	));
});

// form submission function
function vrp_form_submission( WP_REST_Request $request ) {

	$json_data = $request->get_json_params();
	$activity = get_post($json_data['data']['activity_id']);
	$data = wp_json_encode($json_data['data']);

	$postarr = array(
		'post_title' => $json_data['email'],
		'post_date' => $json_data['created_at'],
		'post_content' => $data,
		'post_status' => 'publish',
		'post_type' => 'registratie',
		'comment_status' => 'closed'
	);

	$post_id = wp_insert_post($postarr, $wp_error);

	add_post_meta($post_id, 'activity_id', $activity->ID);

	$response = new WP_REST_Response($post_id);
	$response->set_status(200);

	return $response;
}