<?php 
// This file is generated by Composer
require_once __DIR__ . '/vendor/autoload.php';


$branch 
    = defined('WORDLIFY_BRANCH') 
                ? WORDLIFY_BRANCH 
                : 'master';

$mediaBranch 
    = defined('WORDLIFY_MEDIA_BRANCH') 
                ? WORDLIFY_MEDIA_BRANCH 
                : 'wordlify-media--automatic-branch';


require_once __DIR__ . '/prepareData/prepareData.php';

// 
// Include Github
// 

function github() {
    if (
        defined('WORDLIFY_GIT_HOST') && WORDLIFY_GIT_HOST === 'github'
        ) {
        if (
            !defined('WORDLIFY_GITHUB_API_TOKEN') 
            || (
                defined('WORDLIFY_GITHUB_API_TOKEN') && !WORDLIFY_GITHUB_API_TOKEN
                )
        ) return;
        if (
            !defined('WORDLIFY_GITHUB_OWNER') 
            || (
                defined('WORDLIFY_GITHUB_OWNER') && !WORDLIFY_GITHUB_OWNER
                )
        ) return;
        if (
            !defined('WORDLIFY_GITHUB_REPO') 
            || (
                defined('WORDLIFY_GITHUB_REPO') && !WORDLIFY_GITHUB_REPO
                )
        ) return;
        // If git host is set to github and an owner, api token, and repo is set, include github.
        require_once __DIR__ . "/github/github.php";
    }
}

github();


?>